tests: s/assertEquals/assertEqual/
CI is currently failing with:

Traceback (most recent call last):
  File "/home/user/accountsservice/_build/../tests/test-libaccountsservice.py", line 118, in test_multiple_inflight_get_user_by_id_calls
    self.assertEquals(user.get_user_name(), 'pizza')
    ^^^^^^^^^^^^^^^^^
AttributeError: 'TestAccountsServicePreExistingUser' object has no attribute 'assertEquals'. Did you mean: 'assertEqual'?

I have no idea if assertEquals was dropped, or if CI has been failing
all this time or what.

This commit makes the suggested change.